artistes:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Artistes:index" }

artistes_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:Artistes:show" }

artistes_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Artistes:new" }

artistes_create:
    path:     /create
    defaults: { _controller: "BackOfficeBundle:Artistes:create" }
    methods:  POST

artistes_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:Artistes:edit" }

artistes_update:
    path:     /{id}/update
    defaults: { _controller: "BackOfficeBundle:Artistes:update" }
    methods:  [POST, PUT]

artistes_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:Artistes:delete" }
    requirements:
                            _method:  POST|GET
