<?php

namespace Back\OfficeBundle\Entity;

/**
 * ArtistesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistesRepository extends \Doctrine\ORM\EntityRepository
{
}
