<?php

namespace Back\OfficeBundle\Entity;

/**
 * StructureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StructureRepository extends \Doctrine\ORM\EntityRepository
{
}
