<?php

namespace Back\OfficeBundle\Repository;

/**
 * FonctRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctRepository extends \Doctrine\ORM\EntityRepository
{
}
